sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - stable
  - '6'
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
addons:
  apt:
    packages:
      - unzip
      - tar
script:
  - 'npm run build'
  - 'npm test'
